# Generated by Django 5.2 on 2025-04-29 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securechatapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
