# Generated by Django 5.2 on 2025-04-29 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securechatapp', '0002_message_is_delivered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_delivered',
        ),
    ]
