# Generated by Django 5.2 on 2025-05-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securechatapp', '0006_customuser_date_joined_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptionkey',
            name='private_key',
            field=models.TextField(default=''),
        ),
    ]
