# Generated by Django 5.2 on 2025-05-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securechatapp', '0007_encryptionkey_private_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptionkey',
            name='private_key',
            field=models.TextField(),
        ),
    ]
